# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_create_device <- function(size, seed = NULL) {
    .Call(`_mob_random_create_device`, size, seed)
}

random_uniform_device <- function(rngs, n, min, max) {
    .Call(`_mob_random_uniform_device`, rngs, n, min, max)
}

random_binomial_device <- function(rngs, n, size, prob) {
    .Call(`_mob_random_binomial_device`, rngs, n, size, prob)
}

bernoulli_sampler_device <- function(data, p, seed = NULL) {
    .Call(`_mob_bernoulli_sampler_device`, data, p, seed)
}

homogeneous_infection_process_device <- function(rngs, susceptible, infected, infection_probability) {
    .Call(`_mob_homogeneous_infection_process_device`, rngs, susceptible, infected, infection_probability)
}

partition_create_device <- function(population) {
    .Call(`_mob_partition_create_device`, population)
}

household_infection_process_device <- function(rngs, susceptible, infected, households, infection_probability) {
    .Call(`_mob_household_infection_process_device`, rngs, susceptible, infected, households, infection_probability)
}

selection_sampler_device <- function(data, k, seed = NULL) {
    .Call(`_mob_selection_sampler_device`, data, k, seed)
}

betabinomial_sampler_device <- function(data, k, seed = NULL) {
    .Call(`_mob_betabinomial_sampler_device`, data, k, seed)
}

random_create_host <- function(size, seed = NULL) {
    .Call(`_mob_random_create_host`, size, seed)
}

random_uniform_host <- function(rngs, n, min, max) {
    .Call(`_mob_random_uniform_host`, rngs, n, min, max)
}

random_binomial_host <- function(rngs, n, size, prob) {
    .Call(`_mob_random_binomial_host`, rngs, n, size, prob)
}

homogeneous_infection_process_host <- function(rngs, susceptible, infected, infection_probability) {
    .Call(`_mob_homogeneous_infection_process_host`, rngs, susceptible, infected, infection_probability)
}

partition_create_host <- function(population) {
    .Call(`_mob_partition_create_host`, population)
}

household_infection_process_host <- function(rngs, susceptible, infected, households, infection_probability) {
    .Call(`_mob_household_infection_process_host`, rngs, susceptible, infected, households, infection_probability)
}

bernoulli_sampler_host <- function(data, p, seed = NULL) {
    .Call(`_mob_bernoulli_sampler_host`, data, p, seed)
}

selection_sampler_host <- function(data, k, seed = NULL) {
    .Call(`_mob_selection_sampler_host`, data, k, seed)
}

betabinomial_sampler_host <- function(data, k, seed = NULL) {
    .Call(`_mob_betabinomial_sampler_host`, data, k, seed)
}

run_catch <- function(args = NULL, fork = TRUE) {
    invisible(.Call(`_mob_run_catch`, args, fork))
}

