# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_create_device <- function(size, seed = NULL) {
    .Call(`_mob_random_create_device`, size, seed)
}

random_uniform_device <- function(rngs, n, min, max) {
    .Call(`_mob_random_uniform_device`, rngs, n, min, max)
}

random_poisson_device <- function(rngs, n, lambda) {
    .Call(`_mob_random_poisson_device`, rngs, n, lambda)
}

random_binomial_device <- function(rngs, n, size, prob) {
    .Call(`_mob_random_binomial_device`, rngs, n, size, prob)
}

random_gamma_device <- function(rngs, n, shape, scale) {
    .Call(`_mob_random_gamma_device`, rngs, n, shape, scale)
}

bernoulli_sampler_device <- function(data, p, seed = NULL) {
    .Call(`_mob_bernoulli_sampler_device`, data, p, seed)
}

infection_list_create_device <- function() {
    .Call(`_mob_infection_list_create_device`)
}

homogeneous_infection_process_device <- function(rngs, output, susceptible, infected, infection_probability) {
    .Call(`_mob_homogeneous_infection_process_device`, rngs, output, susceptible, infected, infection_probability)
}

partition_create_device <- function(capacity, population) {
    .Call(`_mob_partition_create_device`, capacity, population)
}

partition_sizes_device <- function(p) {
    .Call(`_mob_partition_sizes_device`, p)
}

ragged_vector_create_device <- function(values) {
    .Call(`_mob_ragged_vector_create_device`, values)
}

ragged_vector_get_device <- function(v, i) {
    .Call(`_mob_ragged_vector_get_device`, v, i)
}

ragged_vector_random_select_device <- function(rngs, data) {
    .Call(`_mob_ragged_vector_random_select_device`, rngs, data)
}

household_infection_process_device <- function(rngs, output, susceptible, infected, households, infection_probability) {
    .Call(`_mob_household_infection_process_device`, rngs, output, susceptible, infected, households, infection_probability)
}

spatial_infection_naive_device <- function(rngs, output, susceptible, infected, x, y, base, k) {
    .Call(`_mob_spatial_infection_naive_device`, rngs, output, susceptible, infected, x, y, base, k)
}

spatial_infection_sieve_device <- function(rngs, output, susceptible, infected, x, y, base, k) {
    .Call(`_mob_spatial_infection_sieve_device`, rngs, output, susceptible, infected, x, y, base, k)
}

spatial_infection_hybrid_device <- function(rngs, output, susceptible, infected, x, y, base, k, width) {
    .Call(`_mob_spatial_infection_hybrid_device`, rngs, output, susceptible, infected, x, y, base, k, width)
}

infection_victims_device <- function(infections, capacity) {
    .Call(`_mob_infection_victims_device`, infections, capacity)
}

infections_as_dataframe_device <- function(infections) {
    .Call(`_mob_infections_as_dataframe_device`, infections)
}

infections_from_dataframe_device <- function(df) {
    .Call(`_mob_infections_from_dataframe_device`, df)
}

infections_select_device <- function(rngs, infections) {
    .Call(`_mob_infections_select_device`, rngs, infections)
}

selection_sampler_device <- function(data, k, seed = NULL) {
    .Call(`_mob_selection_sampler_device`, data, k, seed)
}

betabinomial_sampler_device <- function(data, k, seed = NULL) {
    .Call(`_mob_betabinomial_sampler_device`, data, k, seed)
}

bitset_create_device <- function(capacity) {
    .Call(`_mob_bitset_create_device`, capacity)
}

bitset_clone_device <- function(ptr) {
    .Call(`_mob_bitset_clone_device`, ptr)
}

bitset_size_device <- function(ptr) {
    .Call(`_mob_bitset_size_device`, ptr)
}

bitset_or_device <- function(left, right) {
    invisible(.Call(`_mob_bitset_or_device`, left, right))
}

bitset_remove_device <- function(left, right) {
    invisible(.Call(`_mob_bitset_remove_device`, left, right))
}

bitset_equal_device <- function(left, right) {
    .Call(`_mob_bitset_equal_device`, left, right)
}

bitset_invert_device <- function(ptr) {
    invisible(.Call(`_mob_bitset_invert_device`, ptr))
}

bitset_insert_device <- function(ptr, values) {
    invisible(.Call(`_mob_bitset_insert_device`, ptr, values))
}

bitset_sample_device <- function(ptr, rngs, p) {
    invisible(.Call(`_mob_bitset_sample_device`, ptr, rngs, p))
}

bitset_choose_device <- function(ptr, rngs, k) {
    invisible(.Call(`_mob_bitset_choose_device`, ptr, rngs, k))
}

bitset_to_vector_device <- function(ptr) {
    .Call(`_mob_bitset_to_vector_device`, ptr)
}

alias_table_create_device <- function(weights) {
    .Call(`_mob_alias_table_create_device`, weights)
}

alias_table_values_device <- function(table) {
    .Call(`_mob_alias_table_values_device`, table)
}

alias_table_sample_device <- function(table, rngs, k) {
    .Call(`_mob_alias_table_sample_device`, table, rngs, k)
}

alias_table_sample_wor_device <- function(table, rngs, rows, k) {
    .Call(`_mob_alias_table_sample_wor_device`, table, rngs, rows, k)
}

alias_table_sample_wor_ragged_matrix_device <- function(table, rngs, ks, maxk) {
    .Call(`_mob_alias_table_sample_wor_ragged_matrix_device`, table, rngs, ks, maxk)
}

integer_vector_create_device <- function(values) {
    .Call(`_mob_integer_vector_create_device`, values)
}

integer_vector_values_device <- function(v) {
    .Call(`_mob_integer_vector_values_device`, v)
}

integer_vector_scatter_device <- function(vector, indices, values) {
    invisible(.Call(`_mob_integer_vector_scatter_device`, vector, indices, values))
}

integer_vector_scatter_scalar_device <- function(vector, indices, value) {
    invisible(.Call(`_mob_integer_vector_scatter_scalar_device`, vector, indices, value))
}

integer_vector_scatter_bitset_device <- function(vector, indices, values) {
    invisible(.Call(`_mob_integer_vector_scatter_bitset_device`, vector, indices, values))
}

integer_vector_gather_device <- function(vector, indices) {
    .Call(`_mob_integer_vector_gather_device`, vector, indices)
}

integer_vector_match_eq_device <- function(v, value) {
    .Call(`_mob_integer_vector_match_eq_device`, v, value)
}

integer_vector_match_gt_device <- function(v, value) {
    .Call(`_mob_integer_vector_match_gt_device`, v, value)
}

integer_vector_match_eq_as_bitset_device <- function(v, value) {
    .Call(`_mob_integer_vector_match_eq_as_bitset_device`, v, value)
}

integer_vector_match_gt_as_bitset_device <- function(v, value) {
    .Call(`_mob_integer_vector_match_gt_as_bitset_device`, v, value)
}

integer_vector_add_scalar_device <- function(v, delta) {
    invisible(.Call(`_mob_integer_vector_add_scalar_device`, v, delta))
}

double_vector_create_device <- function(values) {
    .Call(`_mob_double_vector_create_device`, values)
}

double_vector_values_device <- function(v) {
    .Call(`_mob_double_vector_values_device`, v)
}

double_vector_scatter_device <- function(vector, indices, values) {
    invisible(.Call(`_mob_double_vector_scatter_device`, vector, indices, values))
}

double_vector_scatter_scalar_device <- function(vector, indices, value) {
    invisible(.Call(`_mob_double_vector_scatter_scalar_device`, vector, indices, value))
}

double_vector_scatter_bitset_device <- function(vector, indices, values) {
    invisible(.Call(`_mob_double_vector_scatter_bitset_device`, vector, indices, values))
}

double_vector_gather_device <- function(vector, indices) {
    .Call(`_mob_double_vector_gather_device`, vector, indices)
}

double_vector_add_scalar_device <- function(v, delta) {
    invisible(.Call(`_mob_double_vector_add_scalar_device`, v, delta))
}

double_vector_div_scalar_device <- function(v, divisor) {
    invisible(.Call(`_mob_double_vector_div_scalar_device`, v, divisor))
}

double_vector_lround_device <- function(values) {
    .Call(`_mob_double_vector_lround_device`, values)
}

random_create_host <- function(size, seed = NULL) {
    .Call(`_mob_random_create_host`, size, seed)
}

random_uniform_host <- function(rngs, n, min, max) {
    .Call(`_mob_random_uniform_host`, rngs, n, min, max)
}

random_poisson_host <- function(rngs, n, lambda) {
    .Call(`_mob_random_poisson_host`, rngs, n, lambda)
}

random_binomial_host <- function(rngs, n, size, prob) {
    .Call(`_mob_random_binomial_host`, rngs, n, size, prob)
}

random_gamma_host <- function(rngs, n, shape, scale) {
    .Call(`_mob_random_gamma_host`, rngs, n, shape, scale)
}

infection_list_create_host <- function() {
    .Call(`_mob_infection_list_create_host`)
}

homogeneous_infection_process_host <- function(rngs, output, susceptible, infected, infection_probability) {
    .Call(`_mob_homogeneous_infection_process_host`, rngs, output, susceptible, infected, infection_probability)
}

partition_create_host <- function(capacity, population) {
    .Call(`_mob_partition_create_host`, capacity, population)
}

partition_sizes_host <- function(p) {
    .Call(`_mob_partition_sizes_host`, p)
}

ragged_vector_create_host <- function(values) {
    .Call(`_mob_ragged_vector_create_host`, values)
}

ragged_vector_get_host <- function(v, i) {
    .Call(`_mob_ragged_vector_get_host`, v, i)
}

ragged_vector_random_select_host <- function(rngs, data) {
    .Call(`_mob_ragged_vector_random_select_host`, rngs, data)
}

household_infection_process_host <- function(rngs, output, susceptible, infected, households, infection_probability) {
    .Call(`_mob_household_infection_process_host`, rngs, output, susceptible, infected, households, infection_probability)
}

spatial_infection_naive_host <- function(rngs, output, susceptible, infected, x, y, base, k) {
    .Call(`_mob_spatial_infection_naive_host`, rngs, output, susceptible, infected, x, y, base, k)
}

spatial_infection_sieve_host <- function(rngs, output, susceptible, infected, x, y, base, k) {
    .Call(`_mob_spatial_infection_sieve_host`, rngs, output, susceptible, infected, x, y, base, k)
}

spatial_infection_hybrid_host <- function(rngs, output, susceptible, infected, x, y, base, k, width) {
    .Call(`_mob_spatial_infection_hybrid_host`, rngs, output, susceptible, infected, x, y, base, k, width)
}

infection_victims_host <- function(infections, capacity) {
    .Call(`_mob_infection_victims_host`, infections, capacity)
}

infections_as_dataframe_host <- function(infections) {
    .Call(`_mob_infections_as_dataframe_host`, infections)
}

infections_from_dataframe_host <- function(df) {
    .Call(`_mob_infections_from_dataframe_host`, df)
}

infections_select_host <- function(rngs, infections) {
    .Call(`_mob_infections_select_host`, rngs, infections)
}

bernoulli_sampler_host <- function(data, p, seed = NULL) {
    .Call(`_mob_bernoulli_sampler_host`, data, p, seed)
}

selection_sampler_host <- function(data, k, seed = NULL) {
    .Call(`_mob_selection_sampler_host`, data, k, seed)
}

betabinomial_sampler_host <- function(data, k, seed = NULL) {
    .Call(`_mob_betabinomial_sampler_host`, data, k, seed)
}

bitset_create_host <- function(capacity) {
    .Call(`_mob_bitset_create_host`, capacity)
}

bitset_clone_host <- function(ptr) {
    .Call(`_mob_bitset_clone_host`, ptr)
}

bitset_size_host <- function(ptr) {
    .Call(`_mob_bitset_size_host`, ptr)
}

bitset_or_host <- function(left, right) {
    invisible(.Call(`_mob_bitset_or_host`, left, right))
}

bitset_remove_host <- function(left, right) {
    invisible(.Call(`_mob_bitset_remove_host`, left, right))
}

bitset_invert_host <- function(ptr) {
    invisible(.Call(`_mob_bitset_invert_host`, ptr))
}

bitset_equal_host <- function(left, right) {
    .Call(`_mob_bitset_equal_host`, left, right)
}

bitset_insert_host <- function(ptr, values) {
    invisible(.Call(`_mob_bitset_insert_host`, ptr, values))
}

bitset_sample_host <- function(ptr, rngs, p) {
    invisible(.Call(`_mob_bitset_sample_host`, ptr, rngs, p))
}

bitset_choose_host <- function(ptr, rngs, k) {
    invisible(.Call(`_mob_bitset_choose_host`, ptr, rngs, k))
}

bitset_to_vector_host <- function(ptr) {
    .Call(`_mob_bitset_to_vector_host`, ptr)
}

alias_table_create_host <- function(weights) {
    .Call(`_mob_alias_table_create_host`, weights)
}

alias_table_values_host <- function(table) {
    .Call(`_mob_alias_table_values_host`, table)
}

alias_table_sample_host <- function(table, rngs, k) {
    .Call(`_mob_alias_table_sample_host`, table, rngs, k)
}

alias_table_sample_wor_host <- function(table, rngs, rows, k) {
    .Call(`_mob_alias_table_sample_wor_host`, table, rngs, rows, k)
}

alias_table_sample_wor_ragged_matrix_host <- function(table, rngs, ks, maxk) {
    .Call(`_mob_alias_table_sample_wor_ragged_matrix_host`, table, rngs, ks, maxk)
}

integer_vector_create_host <- function(values) {
    .Call(`_mob_integer_vector_create_host`, values)
}

integer_vector_values_host <- function(v) {
    .Call(`_mob_integer_vector_values_host`, v)
}

integer_vector_scatter_host <- function(vector, indices, values) {
    invisible(.Call(`_mob_integer_vector_scatter_host`, vector, indices, values))
}

integer_vector_scatter_scalar_host <- function(vector, indices, value) {
    invisible(.Call(`_mob_integer_vector_scatter_scalar_host`, vector, indices, value))
}

integer_vector_scatter_bitset_host <- function(vector, indices, values) {
    invisible(.Call(`_mob_integer_vector_scatter_bitset_host`, vector, indices, values))
}

integer_vector_gather_host <- function(vector, indices) {
    .Call(`_mob_integer_vector_gather_host`, vector, indices)
}

integer_vector_match_eq_host <- function(v, value) {
    .Call(`_mob_integer_vector_match_eq_host`, v, value)
}

integer_vector_match_gt_host <- function(v, value) {
    .Call(`_mob_integer_vector_match_gt_host`, v, value)
}

integer_vector_match_eq_as_bitset_host <- function(v, value) {
    .Call(`_mob_integer_vector_match_eq_as_bitset_host`, v, value)
}

integer_vector_match_gt_as_bitset_host <- function(v, value) {
    .Call(`_mob_integer_vector_match_gt_as_bitset_host`, v, value)
}

integer_vector_add_scalar_host <- function(v, delta) {
    invisible(.Call(`_mob_integer_vector_add_scalar_host`, v, delta))
}

double_vector_create_host <- function(values) {
    .Call(`_mob_double_vector_create_host`, values)
}

double_vector_values_host <- function(v) {
    .Call(`_mob_double_vector_values_host`, v)
}

double_vector_scatter_host <- function(vector, indices, values) {
    invisible(.Call(`_mob_double_vector_scatter_host`, vector, indices, values))
}

double_vector_scatter_scalar_host <- function(vector, indices, value) {
    invisible(.Call(`_mob_double_vector_scatter_scalar_host`, vector, indices, value))
}

double_vector_scatter_bitset_host <- function(vector, indices, values) {
    invisible(.Call(`_mob_double_vector_scatter_bitset_host`, vector, indices, values))
}

double_vector_gather_host <- function(vector, indices) {
    .Call(`_mob_double_vector_gather_host`, vector, indices)
}

double_vector_add_scalar_host <- function(v, delta) {
    invisible(.Call(`_mob_double_vector_add_scalar_host`, v, delta))
}

double_vector_div_scalar_host <- function(v, divisor) {
    invisible(.Call(`_mob_double_vector_div_scalar_host`, v, divisor))
}

double_vector_lround_host <- function(values) {
    .Call(`_mob_double_vector_lround_host`, values)
}

