# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

device_random_create <- function(size, seed = NULL) {
    .Call(`_mob_device_random_create`, size, seed)
}

parallel_runif <- function(rngs, n, min, max) {
    .Call(`_mob_parallel_runif`, rngs, n, min, max)
}

parallel_rbinom <- function(rngs, n, size, prob) {
    .Call(`_mob_parallel_rbinom`, rngs, n, size, prob)
}

homogeneous_infection_process <- function(rngs, susceptible, infected, infection_probability) {
    .Call(`_mob_homogeneous_infection_process_wrapper`, rngs, susceptible, infected, infection_probability)
}

household_infection_process <- function(rngs, susceptible, infected, households, infection_probability) {
    .Call(`_mob_household_infection_process_wrapper`, rngs, susceptible, infected, households, infection_probability)
}

betabinomial_sampler <- function(data, k, seed = 0L) {
    .Call(`_mob_betabinomial_sampler_wrapper`, data, k, seed)
}

selection_sampler <- function(data, k, seed = 0L) {
    .Call(`_mob_selection_sampler_wrapper`, data, k, seed)
}

bernoulli_sampler <- function(data, p, seed = 0L) {
    .Call(`_mob_bernouilli_sampler_wrapper`, data, p, seed)
}

bernoulli_sampler_count <- function(n, p, seed = 0L) {
    .Call(`_mob_bernouilli_sampler_count_wrapper`, n, p, seed)
}

bernoulli_sampler_gpu <- function(data, p, seed = 0L) {
    .Call(`_mob_bernouilli_sampler_gpu_wrapper`, data, p, seed)
}

bernouilli_sampler_count_gpu <- function(n, p, seed = 0L) {
    .Call(`_mob_bernouilli_sampler_count_gpu_wrapper`, n, p, seed)
}

run_catch <- function(args = NULL, fork = TRUE) {
    invisible(.Call(`_mob_run_catch`, args, fork))
}

